{{- if .Values.instrumentation.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: default-instrumentation
  labels:
    component: opentelemetry-operator
    namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: {{ .Values.instrumentation.exporter_endpoint }}
  propagators:
    - tracecontext
    - baggage
    - b3
  {{- with .Values.instrumentation.sampler }}
  sampler:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
