apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-ebpf.fullname" . }}-config
  labels:
    {{- include "opentelemetry-ebpf.labels" . | nindent 4 }}
data:
  config.yaml: |
    labels:
      environment: {{ tpl (.Values.clusterName | toYaml) . }}
