{{- if and .Values.k8sCollector.enabled .Values.k8sCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector-k8s-collector.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-ebpf.labels" . | nindent 4 }}
{{- end -}}
