{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opentelemetry-collector-kernel-collector.fullname" . }}
  labels:
    {{- include "opentelemetry-ebpf.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "opentelemetry-collector-kernel-collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "opentelemetry-collector-kernel-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
