{{- if and .Values.kernelCollector.enabled .Values.kernelCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector-kernel-collector.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-ebpf.labels" . | nindent 4 }}
{{- end -}}
