apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentelemetry-collector-reducer.fullname" . }}
  labels:
    {{- include "opentelemetry-ebpf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reducer.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "opentelemetry-collector-reducer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- $ports := include "opentelemetry-collector-reducer.servicePortsConfig" . }}
  {{- if $ports }}
  ports:
    {{- $ports | nindent 4}}
  {{- end }}
